# ─────────────────────────────────────────────────────────────────────────
# RDS PostgreSQL — storage for Next.js (Prisma).
#
# Free Tier:
#   - db.t3.micro / db.t4g.micro: 750 hrs/month for 12 months.
#   - 20 GB gp2 + 20 GB free backups.
#   - Multi-AZ is NOT covered by Free Tier — single-AZ by default.
#
# Access:
#   - publicly_accessible = false → only from within the VPC.
#   - Security group accepts 5432/tcp from the SGs we pass in
#     `allowed_security_group_ids` (typically the k3s one).
#
# Password:
#   - Generated by Terraform (random_password) and stored in SSM
#     Parameter Store encrypted with KMS managed key (alias/aws/ssm).
#   - The ec2-k3s module reads it from SSM in user-data and injects it into
#     the Kubernetes Secret — the app only reads DATABASE_URL from env.
# ─────────────────────────────────────────────────────────────────────────

# Random password for the master user.
resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# Store it as SecureString in SSM so ec2-k3s can read it with its
# instance profile (without passing it to flat files in Terraform state).
resource "aws_ssm_parameter" "db_password" {
  name        = "/${var.name}/db/password"
  description = "Master password de RDS Postgres para ${var.name}"
  type        = "SecureString"
  value       = random_password.db.result
  tags        = var.tags

  lifecycle {
    ignore_changes = [value]
  }
}

# Full connection URL, ready to use as DATABASE_URL.
resource "aws_ssm_parameter" "database_url" {
  name        = "/${var.name}/db/url"
  description = "Connection string (DATABASE_URL) for Prisma."
  type        = "SecureString"
  value       = "postgresql://${var.db_username}:${urlencode(random_password.db.result)}@${aws_db_instance.this.address}:${aws_db_instance.this.port}/${var.db_name}?schema=public&sslmode=require"
  tags        = var.tags
}

# ─── Subnet group ─────────────────────────────────────────────────────────
resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-db-subnet-group"
  subnet_ids = var.db_subnet_ids

  tags = merge(var.tags, {
    Name = "${var.name}-db-subnet-group"
  })
}

# ─── Security Group ───────────────────────────────────────────────────────
resource "aws_security_group" "db" {
  name        = "${var.name}-db-sg"
  description = "Postgres 5432 from k3s SG"
  vpc_id      = var.vpc_id

  egress {
    description = "No egress (RDS only responds to whoever talks to it)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(var.tags, {
    Name = "${var.name}-db-sg"
  })
}

resource "aws_security_group_rule" "allow_postgres_from_app" {
  for_each = { for id in var.allowed_security_group_ids : id => id }

  type                     = "ingress"
  description              = "Postgres from app SG"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  source_security_group_id = each.value
  security_group_id        = aws_security_group.db.id
}

# ─── Parameter group: enforce SSL ─────────────────────────────────────────
resource "aws_db_parameter_group" "this" {
  name        = "${var.name}-pg"
  family      = "postgres${split(".", var.engine_version)[0]}"
  description = "Postgres with SSL enforced"

  parameter {
    name  = "rds.force_ssl"
    value = "1"
    apply_method = "pending-reboot"
  }

  tags = var.tags
}

# ─── Instancia ────────────────────────────────────────────────────────────
resource "aws_db_instance" "this" {
  identifier        = "${var.name}-pg"
  engine            = "postgres"
  engine_version    = var.engine_version
  instance_class    = var.instance_class
  allocated_storage = var.allocated_storage_gb
  max_allocated_storage = var.max_allocated_storage_gb > 0 ? var.max_allocated_storage_gb : null
  storage_type      = var.storage_type
  storage_encrypted = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.db.id]
  parameter_group_name   = aws_db_parameter_group.this.name

  publicly_accessible = var.publicly_accessible
  multi_az            = var.multi_az

  backup_retention_period = var.backup_retention_days
  backup_window           = "06:00-07:00"
  maintenance_window      = "sun:07:30-sun:08:30"

  copy_tags_to_snapshot = true
  deletion_protection   = var.deletion_protection
  skip_final_snapshot   = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-pg-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  performance_insights_enabled = false  # Not Free Tier; enable in prod if needed

  apply_immediately = false

  tags = merge(var.tags, {
    Name = "${var.name}-pg"
  })

  lifecycle {
    ignore_changes = [final_snapshot_identifier, password]
  }
}
