apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appointment-scheduling

labels:
  - pairs:
      app.kubernetes.io/name: appointment-scheduling
      app.kubernetes.io/part-of: appointment-scheduling

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

images:
  - name: appointment-scheduling
    newTag: latest
