apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: appointment-scheduling
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: appointment-scheduling
      app.kubernetes.io/component: web
